### ISSUE TITLE
When adding armor to character model, WMVx crashes.

### ISSUE THREAD

**Issue by Cuvhe** [Frostshake/WMVx#37] opened 2024-06-24 00:06 UTC
https://github.com/Frostshake/WMVx/assets/77686519/29cc72ce-bdc9-435e-adae-35f7d7859ea5

**Comment by Frostshake** [comment] 2024-06-25 19:49
Looks to have been caused by db changes in a recent WoW update, will be fixed with next build.

**Comment by Cuvhe** [comment] 2024-06-26 00:22
> Looks to have been caused by db changes in a recent WoW update, will be fixed with next build.

Thank you!

**Comment by Frostshake** [comment] 2024-06-27 19:57
Resolved with v0.3.0

**Closed by Frostshake** 2024-06-27 19:57 UTC
